import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Search from "../components/Search";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>eBay Search Example</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<Search />
			</main>
		</div>
	);
}
